
name: Certificate Authority Test
run-name: Test certificate authority creation by @${{ github.actor }}
on: [push]

jobs:
    ubuntu:
        runs-on: ubuntu-22.04
        steps:
            -   name: checkout repo
                uses: actions/checkout@v2

            -   name: setup python
                uses: actions/setup-python@v4
                with:
                    python-version: '3.10'
            
            -   name: requirements
                run: python -m pip install --upgrade pip && pip install -r requirements.txt

            -   name: run
                run: sudo python main.py
