
name: Certificate Authority Test Ubuntu-22.04
run-name: Test certificate authority creation on Ubuntu 22.04 by @${{ github.actor }}
on: [push]

jobs:
    ubuntu-22:
        runs-on: ubuntu-22.04
        env:
            working-directory: /home/runner/work/certificate-mess/certificate-mess
        steps:
            -   name: checkout repo
                uses: actions/checkout@v2

            -   name: setup python
                uses: actions/setup-python@v4
                with:
                    python-version: '3.10'
            
            -   name: run
                run: sudo python main.py
